default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
        args: [--config=pyproject.toml, --fix]
      - id: ruff-format
        args: [--config=pyproject.toml]

  - repo: local
    hooks:
      - id: mypy
        name: mypy (strict)
        entry: uv run --frozen mypy --config-file=pyproject.toml .
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.18.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/docker-compose-linter/pre-commit-dclint
    rev: v3.1.0
    hooks:
      - id: dclint
        files: ^(docker-)?compose.*\.ya?ml$

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        files: ^\.github/workflows/

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.17
    hooks:
      - id: uv-lock
